FRONTENDSCHOOL6/finalize-react-6

- src/pages/Login.jsx
> markup: 로그인 페이지 마크업 및 스타일링

- src/components/Button.jsx
- src/components/InputField.jsx
- src/components/LinkItem.jsx
- src/components/Logo.jsx
- src/pages/Login.jsx
> react: 컴포넌트 분리

- src/pages/Home.jsx
- src/pages/MyProfile.jsx
> react: helmet title 추가

- src/components/GetKakaoMap.jsx
- src/components/weather/GetTemperature.jsx
- src/pages/TrafficInfo.jsx
> 교통 상황 페이지 마크업 완료했습니다

- src/layout/Header.jsx
> feat: 헤더 fixed 메인 페이지에만 되도록 구현

- src/api/pocketbase.js
- src/components/Button.jsx
- src/components/InputField.jsx
- src/components/login/KakaoLogin.jsx
- src/pages/Login.jsx
- src/utils/validation.js
> [feat] 로그인 기능 구현

- src/components/Button.jsx
- src/pages/Join.jsx
> markup: join 마크업 수정

- src/components/PageHead.jsx
- src/components/content/CommentItem.jsx
- src/pages/content/ContentCreate.jsx
- src/pages/content/ContentDetail.jsx
> [react] 콘텐츠 수정 상세 페이지 수정 및 기능 추가

- src/components/GetKakaoMap.jsx
- src/pages/TrafficInfo.jsx
> feat: 카카오 맵 api

- src/components/weather/ImgSky.jsx
- src/components/weather/OnedayWeather.jsx
- src/components/weather/OnedayWeather2.jsx
- src/components/weather/SelectLocation.jsx
- src/components/weather/WeatherTable.jsx
- src/components/weather/WeatherTable2.jsx
- src/pages/WeatherInfo.jsx
> 3일치 날씨 가져오기 실패..

- index.html
- src/components/Map.jsx
- src/components/content/TagSelect.jsx
- src/pages/Contents.jsx
- src/pages/content/ContentCreate.jsx
- src/pages/content/ContentDetail.jsx
- src/styles/map.css
> [기능 구현] 콘텐츠 등록 페이지 - 카카오맵, 태그

- src/components/GetKakaoMap.jsx
- src/pages/TrafficInfo.jsx
- 장소 검색 기능 구현
- 검색 장소 마커로 표시
- 마커 mouseover → 장소 명 표시
related to: #54
> feat: 교통 정보 표시 기능 추가

- src/components/weather/SelectLocation.jsx
- src/pages/WeatherInfo.jsx
> [날씨 페이지] 문구 수정 및 현재 위치 보여주기

- src/pages/content/ContentDetail.jsx
> design: 상세 페이지 커스텀 태그 보이기

- src/components/MainContent.jsx
- src/components/MainTag.jsx
- src/components/Spinner.jsx
- src/components/weather/GetWeather.jsx
- src/components/weather/ImgSky.jsx
- src/components/weather/OnedayWeather.jsx
- src/components/weather/ThreedaysWeather.jsx
- src/components/weather/WeatherTable.jsx
- src/pages/Home.jsx
로딩 스피너, 메인 페이지 framer motion 기능 구현
> 로딩 스피너, 메인 페이지 framer motion 기능 구현

- src/pages/content/ContentDetail.jsx
> fix: 상세 페이지 지도 초기값 문제 해결

- src/components/content/AddComment.jsx
> 댓글 전송 후 인풋 초기화 작업했습니다.

- src/api/pocketbase.js
- src/components/ProfileComment.jsx
- src/components/content/ContentItem.jsx
- src/pages/MyProfile.jsx
- src/pages/content/ContentDetail.jsx
> [기능 구현] 프로필 페이지 리스트 렌더링 등

- src/components/TitleButton.jsx
- src/pages/MyProfile.jsx
> feat: 프로필 페이지 더보기 버튼 조건 처리

- src/components/ProtectRoute.jsx
- src/components/header/Navigation.jsx
- src/components/join/Modal.jsx
- src/components/join/TermsOfService.jsx
- src/components/login/LoginPageContent.jsx
- src/layout/Header.jsx
- src/layout/RootLayout.jsx
- src/pages/Home.jsx
> [컴포넌트 수정] CSS Style 수정

- src/components/content/AddComment.jsx
- src/components/content/CommentItem.jsx
- src/components/weather/ImgSky.jsx
- src/pages/content/ContentDetail.jsx
- src/routes.jsx
> 댓글 추가, 수정, 삭제

- src/components/MainContent.jsx
- src/components/MainTag.jsx
- src/pages/Home.jsx
> 메인페이지 페이지네이션, 태그 볼드 처리

- src/components/content/AddComment.jsx
> feat: 비로그인 시 댓글 작성 불가 알람

- src/components/content/AddComment.jsx
- src/components/weather/ImgSky.jsx
- src/components/weather/ThreedaysWeatherTable.jsx
- src/components/weather/WeatherTable.jsx
> design: 날씨 페이지 폰트 크기 변경

- src/components/login/KakaoLogin.jsx
- src/hooks/useVerification.js
- 카카오 로그인 시 유저 상태에 id 값 추가
- useVerification scale, caching 타임 조정
> fix: 카카오 로그인, useVerification 수정

- src/components/content/AddComment.jsx
- src/components/content/CommentItem.jsx
- src/components/weather/OnedayWeather.jsx
- src/components/weather/ThreedaysWeather.jsx
- src/pages/content/ContentDetail.jsx
댓글에 시간 추가, 로그인 안했을 때 disabled, 날씨 warning 수정
> 댓글에 시간 추가, 로그인 안했을 때 disabled, 날씨 warning 수정

- src/components/KakaoMap/GetKakaoMap.jsx
- src/pages/Join.jsx
- src/pages/TrafficInfo.jsx
- style: 카카오 맵 검색 Input zIndex 값 수정
> rename: 폴더 이름 변경 KakaoMap -> kakaomap

- pnpm-lock.yaml
- src/components/weather/ImgSky.jsx
- src/components/weather/ThreedaysWeatherTable.jsx
- src/pages/WeatherInfo.jsx
> 날씨 페이지 텐스텍쿼리 사용

- src/components/PageHead.jsx
- src/components/profile/ProfileCommentSection.jsx
- src/components/profile/ProfileContentSection.jsx
- src/pages/content/ContentDetail.jsx
resolves: #168, 
resolves: #163
> helmet 메타데이터 추가 및 프로필 댓글 인피니트 쿼리 변경 등

- src/components/ProtectRoute.jsx
- src/components/ReplaceRoute.jsx
- src/components/login/KakaoLogin.jsx
- src/components/login/LoginPageContent.jsx
- src/layout/Header.jsx
- src/pages/Login.jsx
- src/pages/content/ContentEdit.jsx
- src/pages/finduser/FindId.jsx
- src/routes.jsx
- 토글 버튼을 제외한 영역을 클릭하면 메뉴가 닫히게 수정
- 다른 페이지로 이동 시 메뉴가 닫히게 수정
- 로그인 한 사용자는 로그인/회원가입 페이지 접근 불가
> Fix : 헤더 UX 개선, 로그인 한 사용자 접근 처리

- pnpm-lock.yaml
- src/components/Button.jsx
- src/components/join/Termscheck.jsx
- src/pages/Join.jsx
- 회원 가입 시 닉네임 글자 제한 및 띄어쓰기 방지 기능 구현
- 회원 가입 중복 확인 기능 세부화 (진행 중)
> feat: 회원가입 페이지 기능 추가

- src/components/MainContent.jsx
- src/components/content/AddComment.jsx
- src/components/content/CommentItem.jsx
- src/components/weather/SelectLocation.jsx
- src/components/weather/ThreedaysWeatherTable.jsx
- src/components/weather/WeatherTable.jsx
- src/pages/Home.jsx
- src/pages/WeatherInfo.jsx
- src/pages/content/ContentDetail.jsx
메인 현제 페이지 버튼 색 , 댓글 버튼 크기, 닉네임 너비 수정
> 메인 현제 페이지 버튼 색 , 댓글 버튼 크기, 닉네임 너비 수정

- src/components/login/LoginPageContent.jsx
- src/pages/Join.jsx
아무 입력 값이 들어가도 중복된 값을 반환한다는 에러를 수정했습니다.
> fix: 회원가입 중복확인 에러 수정

- src/App.jsx
- src/components/MainTag.jsx
- src/components/PaginationButton.jsx
- src/layout/RootLayout.jsx
- src/pages/Contents.jsx
- src/pages/Home.jsx
- src/pages/content/ContentCreate.jsx
- src/pages/content/ContentDetail.jsx
- src/pages/content/ContentEdit.jsx
resolves: #194
resolves: #195 
resolves: #196
> [기능 구현+] 모바일 뷰 최적화, 버그 수정 등

- index.html
- src/components/Button.jsx
- src/components/InputField.jsx
- src/components/MainSlide.jsx
- src/components/MainTag.jsx
- src/components/join/Termscheck.jsx
- src/components/login/KakaoLogin.jsx
- src/components/login/LoginPageContent.jsx
- src/pages/Join.jsx
- src/pages/Login.jsx
- src/pages/content/ContentCreate.jsx
- tailwind.config.js
resolves: #199, #200, #201, #202
> [기능 구현+] 로그인, 회원 가입 페이지 모바일 뷰 최적화, 회원 가입 스페이스바 방지 등

- src/pages/finduser/FindId.jsx
- src/pages/finduser/FindPw.jsx
> style: 아이디 찾기, 비밀번호 찾기 페이지 모바일 뷰 최적화

- README.md
- src/components/profile/ProfileCommentSection.jsx
> README 작성 및 기본 댓글 이슈
